spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=SpringJpa;encrypt=true;trustServerCertificate=true
    username: sa
    password: Admin$1
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true